# Generated by Django 4.2.8 on 2024-02-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcaulie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targets',
            old_name='specific',
            new_name='specificity',
        ),
    ]
