# Generated by Django 4.2.8 on 2024-04-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcaulie', '0002_rename_specific_targets_specificity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targets',
            options={'managed': False},
        ),
    ]
